package com.junkfood.seal.util

import androidx.annotation.CheckResult
import com.junkfood.seal.database.objects.SavedVideoInfo
import java.io.File
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * Export helpers for the "Video Info Download" tool's saved cards. Writes a TXT or JSON
 * snapshot of a [SavedVideoInfo] to the app's docs directory (see [FileUtil.getDocsDirectory]),
 * mirroring the naming/formatting conventions of [DownloadUtil.writeDocsTextFile].
 */
object VideoInfoExportUtil {

    private val prettyJson = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    private fun safeFileName(title: String): String =
        title.ifBlank { "video_info" }.replace(Regex("""[<>:"/\\|?*]"""), "_").take(100)

    @CheckResult
    fun exportAsTxt(info: SavedVideoInfo): Result<String> = runCatching {
        val docsDir = FileUtil.getDocsDirectory()
        val file = File(docsDir, "${safeFileName(info.title)} - Info.txt")
        val content = buildString {
            appendLine("═══════════════════════════════════════")
            appendLine("  VIDEO INFORMATION")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("Title:")
            appendLine(info.title)
            appendLine()
            if (info.uploader.isNotBlank()) {
                appendLine("Uploader:")
                appendLine(info.uploader)
                appendLine()
            }
            if (info.uploadDate.isNotBlank()) {
                appendLine("Upload Date:")
                appendLine(info.uploadDate)
                appendLine()
            }
            if (info.durationString.isNotBlank()) {
                appendLine("Duration:")
                appendLine(info.durationString)
                appendLine()
            }
            if (info.viewCount >= 0) {
                appendLine("Views:")
                appendLine(info.viewCount.toString())
                appendLine()
            }
            if (info.likeCount >= 0) {
                appendLine("Likes:")
                appendLine(info.likeCount.toString())
                appendLine()
            }
            if (info.videoUrl.isNotBlank()) {
                appendLine("URL:")
                appendLine(info.videoUrl)
                appendLine()
            }
            if (info.tags.isNotEmpty()) {
                appendLine("Tags:")
                info.tags.forEach { tag -> appendLine("  • $tag") }
                appendLine()
            }
            if (info.description.isNotBlank()) {
                appendLine("Description:")
                appendLine(info.description)
                appendLine()
            }
            appendLine("═══════════════════════════════════════")
            appendLine("  Generated by Cat")
            appendLine("═══════════════════════════════════════")
        }
        FileUtil.writeContentToFile(content, file)
        file.absolutePath
    }

    @CheckResult
    fun exportAsJson(info: SavedVideoInfo): Result<String> = runCatching {
        val docsDir = FileUtil.getDocsDirectory()
        val file = File(docsDir, "${safeFileName(info.title)} - Info.json")
        val exportModel = VideoInfoJsonExport(
            title = info.title,
            description = info.description,
            tags = info.tags,
            videoUrl = info.videoUrl,
            thumbnailUrl = info.thumbnailUrl,
            uploader = info.uploader,
            uploadDate = info.uploadDate,
            duration = info.durationString,
            viewCount = info.viewCount.takeIf { it >= 0 },
            likeCount = info.likeCount.takeIf { it >= 0 },
            extractor = info.extractor,
        )
        val content = prettyJson.encodeToString(exportModel)
        FileUtil.writeContentToFile(content, file)
        file.absolutePath
    }

    @kotlinx.serialization.Serializable
    private data class VideoInfoJsonExport(
        val title: String,
        val description: String,
        val tags: List<String>,
        val videoUrl: String,
        val thumbnailUrl: String,
        val uploader: String,
        val uploadDate: String,
        val duration: String,
        val viewCount: Long?,
        val likeCount: Long?,
        val extractor: String,
    )
}
